'use client';

const VERSION = process.env.NEXT_PUBLIC_APP_VERSION ?? '0.1.0';
const GIT_SHA = process.env.NEXT_PUBLIC_GIT_SHA ?? null;
const REPO = 'https://github.com/ankitjawla/capgenie_reg_search';

export default function Footer() {
  return (
    <footer className="mt-10 border-t border-slate-200 pt-6 text-xs text-slate-500 no-print dark:border-slate-700 dark:text-slate-400">
      <div className="flex flex-wrap items-center justify-between gap-2">
        <div className="flex items-center gap-2">
          <span className="font-semibold text-slate-700 dark:text-slate-300">CapGenie</span>
          <span>·</span>
          <span>v{VERSION}</span>
          {GIT_SHA && (
            <>
              <span>·</span>
              <code className="font-mono text-[10px] text-slate-400">{GIT_SHA.slice(0, 7)}</code>
            </>
          )}
        </div>
        <div className="flex items-center gap-3">
          <a
            href={REPO}
            target="_blank"
            rel="noopener noreferrer"
            className="hover:text-brand-600 dark:hover:text-brand-400"
          >
            GitHub
          </a>
          <a href="/api/health" className="hover:text-brand-600 dark:hover:text-brand-400">
            Health
          </a>
        </div>
      </div>
      <p className="mt-2 max-w-3xl">
        <strong>Advisory only.</strong> CapGenie outputs are generated by AI and reflect a deterministic rules engine over a
        curated catalog. Verify every recommendation with your compliance team before filing anything. Sources cited
        in each analysis are starting points, not certifications.
      </p>
    </footer>
  );
}
