// Shared type definitions for the bank-profile -> reports pipeline.

export type Jurisdiction = 'US' | 'UK' | 'EU' | 'IN' | 'CA' | 'SG' | 'HK';

export type EntityType = 'bank' | 'insurer' | 'crypto_firm';

export type BankCategory =
  | 'commercial_bank'
  | 'investment_bank'
  | 'savings_bank'
  | 'credit_union'
  | 'cooperative_bank'
  | 'foreign_branch'
  | 'bank_holding_company'
  | 'small_finance_bank'
  | 'payments_bank'
  | 'nbfc'
  | 'building_society'
  // Non-bank entity categories (used when entityType !== 'bank')
  | 'life_insurer'
  | 'property_casualty_insurer'
  | 'reinsurer'
  | 'crypto_exchange'
  | 'crypto_custodian'
  | 'stablecoin_issuer'
  | 'other';

export type AssetSizeTier =
  | 'lt_1B'
  | '1B_to_10B'
  | '10B_to_50B'
  | '50B_to_100B'
  | '100B_to_250B'
  | '250B_to_700B'
  | 'gt_700B'
  | 'unknown';

export type Activity =
  | 'retail_deposits'
  | 'commercial_lending'
  | 'mortgage_lending'
  | 'credit_cards'
  | 'derivatives_trading'
  | 'securities_underwriting'
  | 'broker_dealer'
  | 'asset_management'
  | 'custody_services'
  | 'cross_border_payments'
  | 'foreign_exchange'
  | 'trade_finance'
  | 'crypto_assets'
  | 'priority_sector_lending'
  | 'agriculture_lending';

export interface JurisdictionPresence {
  jurisdiction: Jurisdiction;
  // What entity type the bank operates as in that jurisdiction
  entityType: BankCategory;
  // Whether it has a parent holding company there
  hasHoldingCompany?: boolean;
  // For US: is this a Foreign Banking Organization (FBO) presence?
  isFBO?: boolean;
  // Approximate consolidated assets in that jurisdiction (USD billions)
  jurisdictionAssetsUsdB?: number;
  // Notes (city, charter type, regulator subtype)
  notes?: string;
}

export interface BankProfile {
  legalName: string;
  commonName?: string;
  // What kind of entity — bank (default), insurer, or crypto firm.
  // Rules engine forks on this; the deep-agent's planner detects it.
  entityType?: EntityType;
  // Country of headquarters (ISO 3166-1 alpha-2 like "US", "GB", "IN", "DE")
  hqCountry?: string;
  // Approximate global consolidated assets in USD billions
  globalAssetsUsdB?: number;
  // Aggregated profile fields used by the rules engine
  category: BankCategory;
  assetSizeTier: AssetSizeTier;
  isPubliclyListed?: boolean;
  isGSIB?: boolean;
  isDSIB?: boolean;
  isFDICInsured?: boolean;
  hasInsuranceSubsidiary?: boolean;
  hasBrokerDealerSubsidiary?: boolean;
  // List of jurisdictions where the entity has operations
  presence: JurisdictionPresence[];
  activities: Activity[];
  // Free text describing why the model classified the bank this way
  rationale?: string;
  // URLs the model used as citations
  sources?: { title?: string; url: string }[];
}

export type ReportFrequency =
  | 'daily'
  | 'weekly'
  | 'fortnightly'
  | 'monthly'
  | 'quarterly'
  | 'semi_annual'
  | 'annual'
  | 'event_driven'
  | 'ad_hoc';

export interface ReportRecommendation {
  id: string;
  jurisdiction: Jurisdiction;
  regulator: string;
  shortName: string;
  fullName: string;
  description: string;
  frequency: ReportFrequency;
  // Why this report applies to *this* bank, generated by the rules engine
  applicabilityReason: string;
  // Static reference URL
  referenceUrl?: string;
  // Severity: must-file vs. likely vs. conditional
  confidence: 'high' | 'medium' | 'low';
  // Dot-path identifiers of profile fields that triggered this rule — e.g.
  // 'assetSizeTier', 'activities.mortgage_lending', 'presence.US.entityType'.
  // Used to render "Why this report?" drawers and cross-link to sources.
  evidenceFieldIds: string[];
}

export interface SearchStep {
  query: string;
  agent?: string; // which sub-agent fired this — 'planner' | 'researcher' | 'verifier'
  results: { title?: string; url: string; snippet?: string }[];
}

export interface AnalysisTrace {
  // Every web search run during this analysis, in order.
  searches: SearchStep[];
  // Running text transcript of the agent's reasoning (model deltas concatenated).
  assistantText: string;
  // Total node transitions in the graph (roughly: how hard the agent worked).
  turns: number;
  elapsedMs: number;
}

export interface AnalysisResult {
  profile: BankProfile;
  reports: ReportRecommendation[];
  generatedAtIso: string;
  warnings?: string[];
  fromCache?: boolean;
  trace?: AnalysisTrace;
}
